create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  price_per_day integer not null check (price_per_day > 0),
  image_url text not null,
  category text not null,
  location text not null default 'USU Medan',
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rentals (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id),
  renter_id uuid not null references auth.users(id),
  start_date date not null,
  end_date date not null,
  days integer not null check (days between 1 and 7),
  total_price integer not null check (total_price > 0),
  status text not null default 'Menunggu persetujuan',
  created_at timestamptz not null default now()
);

alter table public.items enable row level security;
alter table public.rentals enable row level security;

create unique index if not exists items_title_key on public.items(title);

drop policy if exists "Items dapat dilihat publik" on public.items;
create policy "Items dapat dilihat publik"
on public.items for select to anon, authenticated using (true);

drop policy if exists "Pengguna melihat transaksi sendiri" on public.rentals;
create policy "Pengguna melihat transaksi sendiri"
on public.rentals for select to authenticated
using (auth.uid() = renter_id);

drop policy if exists "Pengguna membuat transaksi sendiri" on public.rentals;
create policy "Pengguna membuat transaksi sendiri"
on public.rentals for insert to authenticated
with check (auth.uid() = renter_id);

insert into public.items (title, description, price_per_day, image_url, category)
select * from (values
  ('Sony Alpha A6400 Kit 16-50mm', 'Kamera mirrorless untuk dokumentasi kegiatan kampus.', 75000, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800', 'Elektronik'),
  ('Jas Lab Kimia + Goggles', 'Perlengkapan praktikum lengkap dan bersih.', 15000, 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800', 'Peralatan Lab'),
  ('Casio FX-991EX Ilmiah', 'Kalkulator ilmiah untuk kuliah dan praktikum.', 10000, 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800', 'Elektronik'),
  ('Raket Badminton', 'Raket badminton ringan untuk olahraga kampus.', 20000, 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800', 'Olahraga'),
  ('Tripod Kamera', 'Tripod stabil untuk foto, video, dan dokumentasi acara.', 18000, 'https://images.unsplash.com/photo-1606986628253-3a2c4bd8541e?w=800', 'Elektronik'),
  ('Buku Kalkulus Dasar', 'Buku referensi kalkulus untuk mahasiswa semester awal.', 8000, 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800', 'Kuliah'),
  ('Helm Proyek', 'Helm keselamatan untuk praktikum lapangan.', 12000, 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800', 'Peralatan Lab'),
  ('Bola Basket', 'Bola basket ukuran standar untuk olahraga kampus.', 15000, 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800', 'Olahraga')
) as seed(title, description, price_per_day, image_url, category)
on conflict (title) do nothing;
