create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rental_id bigint references public.rentals(id) on delete cascade,
  kind text not null,
  title text not null,
  message text not null,
  href text not null default '/notifications',
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  unique (rental_id, kind)
);

alter table public.notifications enable row level security;
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

revoke all on public.notifications from anon;
revoke all on public.notifications from authenticated;
grant select on public.notifications to authenticated;
grant update (is_read) on public.notifications to authenticated;

drop policy if exists "Pengguna melihat notifikasi sendiri" on public.notifications;
create policy "Pengguna melihat notifikasi sendiri"
on public.notifications for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Pengguna membaca notifikasi sendiri" on public.notifications;
create policy "Pengguna membaca notifikasi sendiri"
on public.notifications for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.notify_rental_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item_name text;
begin
  select title into item_name from public.items where id = new.item_id;
  if tg_op = 'INSERT' then
    insert into public.notifications (user_id, rental_id, kind, title, message, href)
    values (new.renter_id, new.id, 'rental_created', 'Permintaan sewa terkirim', 'Permintaan sewa untuk "' || coalesce(item_name, 'Barang sewaan') || '" sedang menunggu persetujuan.', '/transactions')
    on conflict (rental_id, kind) do nothing;
  elsif old.status is distinct from new.status then
    insert into public.notifications (user_id, rental_id, kind, title, message, href)
    values (new.renter_id, new.id, 'rental_status:' || new.status, 'Status sewa diperbarui', 'Status sewa "' || coalesce(item_name, 'Barang sewaan') || '" berubah menjadi ' || new.status || '.', '/transactions')
    on conflict (rental_id, kind) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists rentals_create_notification on public.rentals;
create trigger rentals_create_notification
after insert or update of status on public.rentals
for each row execute function public.notify_rental_change();

insert into public.notifications (user_id, rental_id, kind, title, message, href, created_at)
select r.renter_id, r.id, 'rental_created', 'Permintaan sewa terkirim', 'Permintaan sewa untuk "' || i.title || '" sedang menunggu persetujuan.', '/transactions', r.created_at
from public.rentals r
join public.items i on i.id = r.item_id
on conflict (rental_id, kind) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/jpeg', 'image/png', 'image/webp']::text[])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Pengguna melihat avatar sendiri" on storage.objects;
create policy "Pengguna melihat avatar sendiri"
on storage.objects for select to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Pengguna mengunggah avatar sendiri" on storage.objects;
create policy "Pengguna mengunggah avatar sendiri"
on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

drop policy if exists "Pengguna memperbarui avatar sendiri" on storage.objects;
create policy "Pengguna memperbarui avatar sendiri"
on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

drop policy if exists "Pengguna menghapus avatar sendiri" on storage.objects;
create policy "Pengguna menghapus avatar sendiri"
on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end;
$$;
