create table if not exists public.rental_payments (
  id bigint generated by default as identity primary key,
  rental_id bigint not null unique references public.rentals(id),
  order_id text not null unique,
  amount integer not null check (amount > 0),
  status text not null default 'Mempersiapkan'
    check (status in ('Mempersiapkan', 'Menunggu', 'Dibayar', 'Gagal', 'Kedaluwarsa', 'Dikembalikan')),
  redirect_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists rental_payments_order_idx on public.rental_payments(order_id);
alter table public.rental_payments enable row level security;
revoke all on public.rental_payments from public, anon, authenticated;
grant select on public.rental_payments to authenticated;

drop policy if exists "Peserta melihat pembayaran sewa" on public.rental_payments;
create policy "Peserta melihat pembayaran sewa" on public.rental_payments
for select to authenticated using (
  exists (
    select 1 from public.rentals r
    join public.items i on i.id = r.item_id
    where r.id = rental_id and (r.renter_id = auth.uid() or i.owner_id = auth.uid())
  )
);
