alter table public.items add column if not exists owner_id uuid references auth.users(id) on delete set null;
create index if not exists items_owner_idx on public.items(owner_id);

grant insert on public.items to authenticated;
drop policy if exists "Pemilik menambahkan barang" on public.items;
create policy "Pemilik menambahkan barang" on public.items for insert to authenticated
with check (owner_id = auth.uid() and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('item-photos', 'item-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']::text[])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Pemilik mengunggah foto barang" on storage.objects;
create policy "Pemilik mengunggah foto barang" on storage.objects for insert to authenticated
with check (bucket_id = 'item-photos' and (storage.foldername(name))[1] = auth.uid()::text and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

drop policy if exists "Pemilik melihat transaksi barang" on public.rentals;
create policy "Pemilik melihat transaksi barang" on public.rentals for select to authenticated
using (exists (select 1 from public.items where items.id = rentals.item_id and items.owner_id = auth.uid()));

drop policy if exists "Pengguna membuat transaksi sendiri" on public.rentals;
create policy "Pengguna membuat transaksi sendiri" on public.rentals for insert to authenticated
with check (
  auth.uid() = renter_id
  and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false
  and not exists (select 1 from public.items where items.id = item_id and items.owner_id = auth.uid())
);

create or replace function public.review_rental(p_rental_id bigint, p_status text)
returns void language plpgsql security definer set search_path = public as $$
declare
  reviewed_id bigint;
begin
  if p_status not in ('Disetujui', 'Ditolak') then
    raise exception 'Status tidak valid';
  end if;
  update public.rentals r set status = p_status
  from public.items i
  where r.id = p_rental_id and r.item_id = i.id and i.owner_id = auth.uid()
    and r.status = 'Menunggu persetujuan'
    and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false
  returning r.id into reviewed_id;
  if reviewed_id is null then
    raise exception 'Permintaan tidak ditemukan atau sudah diproses';
  end if;
end;
$$;
revoke all on function public.review_rental(bigint, text) from public, anon;
grant execute on function public.review_rental(bigint, text) to authenticated;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  rental_id bigint not null references public.rentals(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists messages_rental_created_idx on public.messages(rental_id, created_at, id);
alter table public.messages enable row level security;
revoke all on public.messages from anon;
revoke all on public.messages from authenticated;
grant select, insert on public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

drop policy if exists "Peserta melihat chat sewa" on public.messages;
create policy "Peserta melihat chat sewa" on public.messages for select to authenticated
using (exists (
  select 1 from public.rentals r join public.items i on i.id = r.item_id
  where r.id = messages.rental_id and (r.renter_id = auth.uid() or i.owner_id = auth.uid())
));

drop policy if exists "Peserta mengirim chat sewa" on public.messages;
create policy "Peserta mengirim chat sewa" on public.messages for insert to authenticated
with check (
  sender_id = auth.uid()
  and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false
  and exists (
    select 1 from public.rentals r join public.items i on i.id = r.item_id
    where r.id = messages.rental_id and (r.renter_id = auth.uid() or i.owner_id = auth.uid())
  )
);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
end;
$$;

create or replace function public.notify_rental_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  item_name text;
  item_owner uuid;
begin
  select title, owner_id into item_name, item_owner from public.items where id = new.item_id;
  if tg_op = 'INSERT' then
    insert into public.notifications (user_id, rental_id, kind, title, message, href)
    values (new.renter_id, new.id, 'rental_created', 'Permintaan sewa terkirim', 'Permintaan sewa untuk "' || coalesce(item_name, 'Barang sewaan') || '" sedang menunggu persetujuan.', '/transactions')
    on conflict (rental_id, kind) do nothing;
    if item_owner is not null and item_owner <> new.renter_id then
      insert into public.notifications (user_id, rental_id, kind, title, message, href)
      values (item_owner, new.id, 'owner_rental_created', 'Permintaan sewa baru', 'Ada permintaan sewa untuk "' || coalesce(item_name, 'Barang sewaan') || '".', '/lend')
      on conflict (rental_id, kind) do nothing;
    end if;
  elsif old.status is distinct from new.status then
    insert into public.notifications (user_id, rental_id, kind, title, message, href)
    values (new.renter_id, new.id, 'rental_status:' || new.status, 'Status sewa diperbarui', 'Status sewa "' || coalesce(item_name, 'Barang sewaan') || '" berubah menjadi ' || new.status || '.', '/transactions')
    on conflict (rental_id, kind) do nothing;
  end if;
  return new;
end;
$$;

create or replace function public.notify_new_message()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  recipient uuid;
  item_name text;
begin
  select case when new.sender_id = r.renter_id then i.owner_id else r.renter_id end, i.title
  into recipient, item_name
  from public.rentals r join public.items i on i.id = r.item_id where r.id = new.rental_id;
  if recipient is not null and recipient <> new.sender_id then
    insert into public.notifications (user_id, rental_id, kind, title, message, href)
    values (recipient, new.rental_id, 'message:' || new.id, 'Pesan baru', 'Ada pesan baru tentang "' || coalesce(item_name, 'Barang sewaan') || '".', '/chat/' || new.rental_id)
    on conflict (rental_id, kind) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists messages_create_notification on public.messages;
create trigger messages_create_notification after insert on public.messages
for each row execute function public.notify_new_message();
