create table if not exists public.rental_reviews (
  id bigint generated by default as identity primary key,
  rental_id bigint not null unique references public.rentals(id) on delete cascade,
  item_id bigint not null references public.items(id),
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null default '' check (comment = '' or char_length(trim(comment)) between 10 and 500),
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists rental_reviews_item_idx on public.rental_reviews(item_id, created_at desc);
alter table public.rental_reviews enable row level security;
revoke all on public.rental_reviews from public, anon, authenticated;
grant select on public.rental_reviews to authenticated;
grant insert (rental_id, item_id, reviewer_id, rating, comment) on public.rental_reviews to authenticated;
grant usage, select on sequence public.rental_reviews_id_seq to authenticated;

drop policy if exists "Penyewa melihat ulasan sendiri" on public.rental_reviews;
create policy "Penyewa melihat ulasan sendiri" on public.rental_reviews
for select to authenticated using (reviewer_id = auth.uid());

drop policy if exists "Penyewa mengulas sewa selesai" on public.rental_reviews;
create policy "Penyewa mengulas sewa selesai" on public.rental_reviews
for insert to authenticated with check (
  reviewer_id = auth.uid()
  and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false
  and exists (
    select 1 from public.rentals r
    where r.id = rental_id and r.item_id = item_id
      and r.renter_id = auth.uid() and r.status = 'Selesai'
  )
);

create table if not exists public.rental_reports (
  id bigint generated by default as identity primary key,
  rental_id bigint not null references public.rentals(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('Barang rusak', 'Tidak sesuai deskripsi', 'Terlambat', 'Lainnya')),
  details text not null check (char_length(trim(details)) between 20 and 1000),
  status text not null default 'Baru' check (status in ('Baru', 'Diproses', 'Selesai')),
  created_at timestamptz not null default now(),
  unique (rental_id, reporter_id)
);

create index if not exists rental_reports_reporter_idx on public.rental_reports(reporter_id, created_at desc);
alter table public.rental_reports enable row level security;
revoke all on public.rental_reports from public, anon, authenticated;
grant select on public.rental_reports to authenticated;
grant insert (rental_id, reporter_id, reason, details) on public.rental_reports to authenticated;
grant usage, select on sequence public.rental_reports_id_seq to authenticated;

drop policy if exists "Pelapor melihat laporan sendiri" on public.rental_reports;
create policy "Pelapor melihat laporan sendiri" on public.rental_reports
for select to authenticated using (reporter_id = auth.uid());

drop policy if exists "Peserta melaporkan masalah sewa" on public.rental_reports;
create policy "Peserta melaporkan masalah sewa" on public.rental_reports
for insert to authenticated with check (
  reporter_id = auth.uid()
  and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false
  and exists (
    select 1 from public.rentals r
    join public.items i on i.id = r.item_id
    where r.id = rental_id and (r.renter_id = auth.uid() or i.owner_id = auth.uid())
  )
);

create or replace view public.item_rating_summary with (security_barrier = true) as
select item_id, count(*)::integer as rating_count, round(avg(rating)::numeric, 1) as rating_average
from public.rental_reviews group by item_id;

create or replace view public.published_item_reviews with (security_barrier = true) as
select id, item_id, rating, comment, created_at
from public.rental_reviews where is_published and comment <> '';

revoke all on public.item_rating_summary, public.published_item_reviews from public, anon, authenticated;
grant select on public.item_rating_summary, public.published_item_reviews to anon, authenticated;
