create table if not exists public.premium_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id text not null unique,
  amount integer not null default 20000 check (amount = 20000),
  status text not null default 'Mempersiapkan'
    check (status in ('Mempersiapkan', 'Menunggu', 'Dibayar', 'Gagal', 'Kedaluwarsa', 'Dikembalikan')),
  redirect_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  membership_applied_at timestamptz
);

create unique index if not exists premium_payments_one_pending_per_user
  on public.premium_payments(user_id)
  where status in ('Mempersiapkan', 'Menunggu');
create index if not exists premium_payments_user_created_idx
  on public.premium_payments(user_id, created_at desc);

create table if not exists public.premium_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_from timestamptz not null,
  active_until timestamptz not null,
  latest_payment_id bigint not null references public.premium_payments(id),
  check (active_until > active_from)
);

alter table public.premium_payments enable row level security;
alter table public.premium_memberships enable row level security;
revoke all on public.premium_payments, public.premium_memberships from public, anon, authenticated;
grant select on public.premium_payments, public.premium_memberships to authenticated;

drop policy if exists "Pengguna dan admin melihat pembayaran Premium" on public.premium_payments;
create policy "Pengguna dan admin melihat pembayaran Premium" on public.premium_payments
for select to authenticated using (
  user_id = auth.uid() or auth.jwt()->'app_metadata'->>'seru_role' = 'admin'
);

drop policy if exists "Pengguna dan admin melihat status Premium" on public.premium_memberships;
create policy "Pengguna dan admin melihat status Premium" on public.premium_memberships
for select to authenticated using (
  user_id = auth.uid() or auth.jwt()->'app_metadata'->>'seru_role' = 'admin'
);

create or replace function public.apply_premium_payment()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from 'Dibayar' and new.status = 'Dibayar' then
    insert into public.premium_memberships (user_id, active_from, active_until, latest_payment_id)
    values (new.user_id, now(), now() + interval '1 month', new.id)
    on conflict (user_id) do update set
      active_from = case when public.premium_memberships.active_until > now()
        then public.premium_memberships.active_from else now() end,
      active_until = greatest(public.premium_memberships.active_until, now()) + interval '1 month',
      latest_payment_id = new.id;
    update public.premium_payments set membership_applied_at = now() where id = new.id;
    insert into public.notifications (user_id, kind, title, message, href)
    values (new.user_id, 'premium_paid:' || new.id, 'SERU Premium aktif',
      'Keanggotaan Premium bertambah satu bulan. Komisi 5% berlaku untuk pesanan yang disetujui selama masa aktif.', '/premium');
  elsif old.status = 'Dibayar' and new.status = 'Dikembalikan' then
    update public.premium_memberships set active_until = now()
    where user_id = new.user_id and latest_payment_id = new.id and active_until > now();
    insert into public.notifications (user_id, kind, title, message, href)
    values (new.user_id, 'premium_refund:' || new.id, 'Pembayaran Premium dikembalikan',
      'Masa aktif dari pembayaran terakhir dihentikan. Periksa status keanggotaanmu.', '/premium');
  end if;
  return new;
end;
$$;

drop trigger if exists premium_payment_applies_membership on public.premium_payments;
create trigger premium_payment_applies_membership
after update of status on public.premium_payments
for each row execute function public.apply_premium_payment();

alter table public.rentals
  add column if not exists platform_fee_bps integer not null default 1000
    check (platform_fee_bps in (500, 1000));

create or replace function public.lock_rental_platform_fee()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  rental_owner uuid;
begin
  if tg_op = 'INSERT' then
    new.platform_fee_bps := 1000;
    return new;
  end if;
  if old.status = 'Menunggu persetujuan' and new.status = 'Disetujui' then
    select owner_id into rental_owner from public.items where id = new.item_id;
    new.platform_fee_bps := case when exists (
      select 1 from public.premium_memberships m
      where m.user_id = rental_owner and m.active_from <= now() and m.active_until > now()
    ) then 500 else 1000 end;
  elsif new.platform_fee_bps is distinct from old.platform_fee_bps then
    raise exception 'Tarif platform tidak dapat diubah setelah persetujuan';
  end if;
  return new;
end;
$$;

drop trigger if exists rentals_lock_platform_fee on public.rentals;
create trigger rentals_lock_platform_fee
before insert or update of status, platform_fee_bps on public.rentals
for each row execute function public.lock_rental_platform_fee();

create or replace function public.create_rental_payout()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  payout_owner uuid;
  payout_gross integer;
  payout_fee integer;
begin
  if new.status <> 'Selesai' or old.status = 'Selesai' then
    return new;
  end if;
  select i.owner_id, p.amount into payout_owner, payout_gross
  from public.items i
  join public.rental_payments p on p.rental_id = new.id
  where i.id = new.item_id and p.status = 'Dibayar' and p.amount = new.total_price;
  if payout_owner is null then
    return new;
  end if;
  payout_fee := ((payout_gross::bigint * new.platform_fee_bps) / 10000)::integer;
  insert into public.rental_payouts
    (rental_id, owner_id, gross_amount, fee_bps, platform_fee, owner_amount, status)
  values (new.id, payout_owner, payout_gross, new.platform_fee_bps, payout_fee, payout_gross - payout_fee,
    case when exists (select 1 from public.rental_reports where rental_id = new.id and status <> 'Selesai')
      then 'Perlu peninjauan' else 'Menunggu simulasi' end)
  on conflict (rental_id) do nothing;
  return new;
end;
$$;
